# Pandas & Numpy

* 運算速度快
* 消耗資源少，採用矩陣運算
* 函式庫中有很多方便好用的資料分析工具

pip install

# numpy

* 裝載相同類型資料的多維度陣列，通常會稱一維陣列為向量(vector)，二維陣列為矩陣(matrix)
* 常使用於機器學習(深度學習、神經網路)
* 資料科學分析數據
* 參考：https://medium.com/python4u/hello-numpy-b5ebe67a1ada

In [2]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4]) # 建立一維陣列，list、tuple皆可
print(a)
print('-----')
b = np.array([(2.5, 1, 3, 4.5), (5, 6, 7, 8)], dtype = float)  # 二維陣列, type可加可不加
print(b)
print('-----')
c = np.array([[(2.5, 1, 3, 4.5), (5, 6, 7, 8)], [(2.5, 1, 3, 4.5), (5, 6, 7, 8)]])  #三維陣列建立
print(c)

In [ ]:
a = np.zeros((2, 3)) # 2x3全為0的陣列
print(a, '\n-----')
b = np.ones((2, 3, 4)) # 2x3x4全為1的陣列
print(b, '\n-----')
c = np.full((3,2), 8) # 3x2全為8的陣列
print(c, '\n-----')
d = np.eye(2)  # 2x2的單位矩陣
print(d, '\n-----')
e = np.random.random((2,3))  # 2x3隨機值(0~1)的矩陣
print(e)

In [3]:
a = np.ones((2, 3, 4))
print(a)
print(a.shape) # 陣列維度
print(len(a)) # 陣列長度(x)
print(a.ndim) # 陣列維度大小(number of dimensions)
print(a.size) # 陣列元素數量

a = a.astype(str) # 更換元素類別
print(a)
print('=======')
b = a.reshape(4, 6)
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)
2
3
24
[[['1.0' '1.0' '1.0' '1.0']
  ['1.0' '1.0' '1.0' '1.0']
  ['1.0' '1.0' '1.0' '1.0']]

 [['1.0' '1.0' '1.0' '1.0']
  ['1.0' '1.0' '1.0' '1.0']
  ['1.0' '1.0' '1.0' '1.0']]]
[['1.0' '1.0' '1.0' '1.0' '1.0' '1.0']
 ['1.0' '1.0' '1.0' '1.0' '1.0' '1.0']
 ['1.0' '1.0' '1.0' '1.0' '1.0' '1.0']
 ['1.0' '1.0' '1.0' '1.0' '1.0' '1.0']]


In [ ]:
# index
a = np.array([1, 2, 3, 4])
print(a[0])
print(a[0:2])
print('-------')
b = np.array([(2.5, 1, 3, 4.5), (5, 6, 7, 8)])
print(b[1])
print(b[1, 3])
print(b[0:, :2])

In [ ]:
a = np.array([[1, 2], [1, 2]])
b = np.array([[2, 4], [2, 4]])
print(np.add(a, b))     #等同a+b
print(a+b)
print('---')
print(np.subtract(a, b)) #等同a-b
print('---')
print(np.multiply(a, b)) #等同a*b
print(a.dot(b)) #矩陣乘法
print('---')
print(np.divide(a, b)) #等同a/b

In [ ]:
a = np.array([(2.5, 1, 3, 4.5), (5, 6, 7, 8)]) # 多維必須思考軸的對應

print(a.sum(axis=0))
print(a.min(axis=1))
print(a.max(axis=0))
print('---')
print(np.median(a, axis=0))
print(np.mean(a, axis=1))
print(np.std(a, axis=0))

# Pandas
* 等同於表格(ex:excel)，有column、row
* pandas為基於numpy產生的套件，使用大量資料運算時較能表現佳
* 參考：https://oranwind.org/python-pandas-ji-chu-jiao-xue/

In [4]:
import pandas as pd

In [ ]:
# Series
# 索引標籤(index)和實際值的陣列組合
series_1 = pd.Series([2, 1, 7, 3])

print(series_1)
print(series_1[2])

In [5]:
dict = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor2": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict, index = dict.keys())
print(select)
print("=====")
print(select[0])  # 利用index找值
print("=====")  
print(select['sensor1'])  # 利用index(自定義)找值
print("=====")  
print(select[[0, 2, 4]])  
print("=====")  
print(select[['factory', 'sensor1', 'sensor3']])

factory    Taipei
sensor1         1
sensor2         2
sensor3         3
sensor4         4
sensor5         5
dtype: object
=====
Taipei
=====
1
=====
factory    Taipei
sensor2         2
sensor4         4
dtype: object
=====
factory    Taipei
sensor1         1
sensor3         3
dtype: object


In [ ]:
# DataFrame
# 類似試算表和關聯式資料庫資料表（table）欄列結構
# 開excel
dataframe_1 = pd.read_csv('pandas_sample.csv') # 讀檔
print(dataframe_1)
#dataframe_1.to_csv('pandas_sample.csv') # 存檔

In [6]:
# 創立dataframe
# from dict
groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num}

df = pd.DataFrame(dict)
print(df)

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58


In [7]:
# from list
df = pd.DataFrame(columns = ['groups', 'num'])
df['groups'] = groups
df['num'] = num
print(df)

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58


In [8]:
# from numpy
df = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'])
print(df)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0


In [9]:
print(df.shape) # 回傳列數與欄數  
print('---')
print(df.head(3)) # 回傳前三筆值  
print('---')  
print(df.tail(3)) # 回傳後三筆值  
print('---')  
print(df.columns) # 回傳欄位名稱  
print('---')  
print(df.index) # 回傳 index  
print('---')  
print(df.info) # 回傳資料內容

(3, 4)
---
     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
---
     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
---
Index(['a', 'b', 'c', 'd'], dtype='object')
---
RangeIndex(start=0, stop=3, step=1)
---
<bound method DataFrame.info of      a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0>


In [ ]:
print(type(df["num"])) # 整列為series型態

list_num  = list(df['num']) # 常轉為list使用
print(type(list_num))

In [ ]:
# iloc 先行後列，利用索引找值

print(df.iloc[0, 1]) # 第一列第二欄：組的人數  
print("---")  
print(df.iloc[0:1,:]) # 第一列：組的組名與人數  
print("---")  
print(df.iloc[:,1]) # 第二欄：各組的人數  
print('---')
print(df.iloc[[0, 3],[0, 1]]) # 第1, 3行、第0, 1列資料
print("---")  
# []選擇元素
print(df["num"]) # 各組的人數  
print("---")  
print(df.num) # 各組的人數
print('---')
print(df['num'][0:4])

In [ ]:
# loc 先行後列，利用欄名找值
# 這部分列名(index)為數字編號，若index為名稱用法相同

print(df.head())
print('---')
print(df.loc[0, 'num']) # 第一列第二欄(num)的人數  
print("---")  
print(df.loc[0:1,:]) # 第一列
print("---")  
print(df.loc[0:2,'groups':'num']) # 第0~2行、第'groups'~ 'num'欄資料
print("---")  
print(df.loc[[1, 3], ['groups', 'num']]) # 第1, 3行、第'groups', 'num'欄資料

In [ ]:
# 操作index
print(df)
print('---')

out_df = df[df.loc[:,"num"] > 10] # 選出人數超過 10 的群組(index為原本)  
print(out_df)
print('---')

out_df2 = out_df.reset_index(drop=True) # 重新編排索引，將原本index刪除(drop)
print(out_df2)
print('---')

out_df3 = out_df.reset_index(drop=False) # 重新編排索引，保留原本index
print(out_df3)
print('---')

out_df4 = out_df.copy()
out_df4.set_index('groups', inplace=True) # 將某欄設為index (取代原本dataframe)
print(out_df4)
print('---')

out_df5 = out_df.copy()
out_df5 = out_df5.set_index('groups', inplace=False) # 將某欄設為index (不取代原本dataframe)
print(out_df5)
print(out_df)

In [ ]:
# sort_values
df_sort = df.sort_values(by = 'num') # 也可以為 groups  
print(df_sort)

In [ ]:
# 處理空值
print(dataframe_1)

In [ ]:
drop_value = dataframe_1.dropna() # 有遺失值的觀測值都刪除(整行刪除)  
print(drop_value)  
print("---")  
filled_value = dataframe_1.fillna(0) # 有遺失值的觀測值填補 0  
print(filled_value)  
print("---")  
filled_value_column = dataframe_1.fillna({"student": "NULL", "english": 0}) # 依欄位填補遺失值  
print(filled_value_column)

In [ ]:
english_value = dataframe_1[dataframe_1['english'].notnull()]
print(english_value)

In [ ]:
# 迭代 and 新增
# for loop

total = []
for i in range(len(dataframe_1)):
    total.append(dataframe_1['math'][i] + dataframe_1['english'][i] + dataframe_1['science'][i])
    
print(total)
dataframe_1['total 1'] = total
print(dataframe_1)

In [ ]:
# iterrows() return(index, row data and its column name(series))
'''
0
student            Jack
id                    1
math                 80
english              20
science              61
description    positive
class                2A
total 1             161
Name: 0, dtype: object
'''
total = []
for i, row in dataframe_1.iterrows():
    total.append(row['math'] + row['english'] + row['science'])
dataframe_1['total 2'] = total
print(dataframe_1)

In [ ]:
# pandas 可直接整列運算
dataframe_1['total 3'] = dataframe_1['math'] + dataframe_1['english'] + dataframe_1['science']
print(dataframe_1)
print(dataframe_1.columns)

In [ ]:
# 新增行
dataframe_2 = pd.DataFrame([('student', 'id', 'math', 'english', 'science', 'description', 'class',
       'total 1', 'total 2', 'total 3')],
    columns=['student', 'id', 'math', 'english', 'science', 'description', 'class',
       'total 1', 'total 2', 'total 3'])
print(dataframe_2)
print('---')
dataframe_3 = dataframe_1.append(dataframe_2, ignore_index=True) # 自動更新index
print(dataframe_3)
print('---')
dataframe_4 = dataframe_1.append([dataframe_2, dataframe_2], ignore_index=True) # 更新多個
print(dataframe_4)

# test (exercise3_file)

* 操作 pandas
* avg:加權平均(math*2, eng*1.5, chinese*1.5)
* type:看哪科最高(math:A, eng:B, chinese:C)
* 小提示:查查idxmax怎麼用

In [ ]:
# concat & merge (額外但常用) 
# http://violin-tao.blogspot.com/2017/06/pandas-2-concat-merge.html

# concat
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
print(df1)
print(df2)

In [ ]:
res = pd.concat([df1,df2],axis=0) #axis=0以直向合併
print(res)
print('---')
res = pd.concat([df1,df2],axis=1) #axis=1以橫向合併
print(res)
print('---')
res = pd.concat([df1,df2],axis=0, ignore_index=True) # 自動產生新的index
print(res)

In [ ]:
# merge
left = pd.DataFrame({
    'key':['K0','K1','K3'],
    'A':['A0','A1','A3'],
    'B':['B0','B1','B3']})

right = pd.DataFrame({
    'key':['K0','K1','K2'],
    'C':['C0','C1','C2'],
    'D':['D0','D1','D2']})
print(left)
print('---')
print(right)

In [ ]:
res = pd.merge(left,right, on='key') # 基於key把left和right合併(只合併共同存在的key)，也可有多個key(利用[])
print(res)

In [ ]:
res = pd.merge(left,right, on='key', how='inner') # inner，符合的合併
print(res)
print('---')
res = pd.merge(left,right, on='key', how='outer') # outer，不合的部分也留下
print(res)

In [ ]:
res = pd.merge(left,right, on='key', how='left')  # 以left為準
print(res)
print('---')
res = pd.merge(left,right, on='key', how='right') # 以right為準
print(res)

# Homework Exercise2

* 上次為搜尋單一檔案
* 此次擴大成搜尋全部檔案(22個)並輸出成如檔案格式:[output file](https://drive.google.com/file/d/1f5CkBfPkYlTVVGEeugHbWSfmqlzbdskM/view?usp=sharing)
* 一樣可供使用者輸入
* 輸出檔說明:track為每個檔案名以及'相同組別之組別名稱'，ave為ratio平均(若為整組部分則為其所有組員之平均)，number為符合條件之數量，all data為所有ratio
* 計時